import { Inter as FontSans } from "next/font/google"
import Navigation from "@/components/navigation";
import "./globals.css";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navigation className="p-2" />
        <main className="flex-grow p-4 justify-center">{children}</main>
      </body>
    </html>
  );
}
